title = "Example Problem"
uuid = "fda28524-3b6f-487f-9ccc-b3236c4d6638"
statementFile = "statement.md"
rating = 1

[languages.lean3]
rootDir = "lean3"
defsFile = "defs.lean"
skeletonFile = "skeleton.lean"
checkFile = "check.lean"
