title = "Example Problem"
uuid = "056bffcc-6528-409e-b764-4883428c1dbb"
statementFile = "statement.md"
rating = 1

[languages.lean3]
rootDir = "lean3"
defsFile = "defs.lean"
skeletonFile = "skeleton.lean"
checkFile = "check.lean"
